version: '3'

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=your_matomo_password
    volumes:
      - mysql:/var/lib/mysql

  app:
    image: matomo
    depends_on:
      - db
    links:
      - db
    volumes:
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_DBNAME=matomo
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=your_matomo_password
    ports:
      - 8080:80

volumes:
  mysql:
  matomo:

